config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles, except: [:delete] do
    resources :comments
  end
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: { minimum: 20 }
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    #where
    #Article.where.not("id = ?",params[:id])
  end

  def new
   @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<div style="width:80%;margin:0 auto;">

  <h1><%=name%></h1>
  <%= form_for(@article) do |f| %>
    <% @article.errors.full_messages.each do |message|%>
    <div class="be-red white top-space">
      * <%=message%>
    </div>
    <%end%>

    <div class="field">
      <%= f.text_field :title, placeholder: "Titulo del artículo", class:"form-control" %>
    </div>

    <div class="field">
      <%= f.text_field :body, placeholder: "Escribe aqui el articulo", style:"height:250px;", class:"form-control" %>
    </div>

    <div class="field">
      <%=f.submit "Guardar", class:"btn be-red white large-padding"%>
    </div>

  <% end %>

</div>

app/views/articles/edit.html.erb
<%= render "form", name: "Editar" %>

app/views/articles/index.html.erb
<% @articles.each do |article|%>
<h1> <%= link_to article.title, article %> </h1>
<div>
  nro de visitas <%= article.visits_count %>
</div>
<div>
  <%= link_to :"Eliminar", article, method: :delete, class: "red", confirm: "Are you sure?", disable_with: "Processing..."  %>
</div>
<% end %>

  <%=link_to "articles/new" do%>
    <div class="be-red white btn">
      Nuevo
    </div>
  <% end %>

app/views/articles/new.html.erb
<%= render "form", name: "Crear un nuevo articulo" %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  <%= @article.body %>
</p>



<h2>
  Escrito por <%= @article.user.email %>
</h2>



<div>
  <%=link_to "Editar",  edit_article_path(@article)  %>
</div>

<h3>Comentarios</h3>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :article_id %>
    <%= form.text_field :article_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.article_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog1</title>

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;700&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%=render "partials/navigation"%>

    <div class="container">
      <%= yield %>
    </div>


  </body>
</html>

app/views/partials/_navigation.erb
<header>
      <nav class="be-red white large-padding">
        <ul class="no-list row center-xs">
          <li class="col-md">
            <%= link_to "Inicio", root_path %>
          </li>
          <li class="col-md">
            <%= link_to "Posts", articles_path %>
          </li>
          <li class="col-md">
            <%= link_to "Nuevo Post", new_article_path %>
          </li>

          <%if user_signed_in? %>
            <li class="col-md">
              <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="col-md">
              <%= link_to "Iniciar sesion", new_user_session_path %>
            </li>
            <li class="col-md">
              <%= link_to "Crear cuenta", new_user_registration_path %>
            </li>

          <%end%>
        </ul>
      </nav>
    </header>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  <h1>bienvenido <%= current_user.email %></h1>
  <% else %>
  <h1>Registrate en nuestra nueva plataforma</h1>
<% end %>